
package com.album.dispatcher;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AlbumService", targetNamespace = "http://album.com/dispatcher", wsdlLocation = "http://picasa.com/wsdl")
public class AlbumService
    extends Service
{

    private final static URL ALBUMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.album.dispatcher.AlbumService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.album.dispatcher.AlbumService.class.getResource(".");
            url = new URL(baseUrl, "http://picasa.com/wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://picasa.com/wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ALBUMSERVICE_WSDL_LOCATION = url;
    }

    public AlbumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlbumService() {
        super(ALBUMSERVICE_WSDL_LOCATION, new QName("http://album.com/dispatcher", "AlbumService"));
    }

    /**
     * 
     * @return
     *     returns Album
     */
    @WebEndpoint(name = "AlbumServicePort")
    public Album getAlbumServicePort() {
        return super.getPort(new QName("http://album.com/dispatcher", "AlbumServicePort"), Album.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Album
     */
    @WebEndpoint(name = "AlbumServicePort")
    public Album getAlbumServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://album.com/dispatcher", "AlbumServicePort"), Album.class, features);
    }

}
