
package com.album.dispatcher;

import javax.xml.ws.WebFault;
import org.w3._2005.atom.LoginFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://www.w3.org/2005/Atom")
public class ClientLoginFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LoginFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ClientLoginFault(String message, LoginFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ClientLoginFault(String message, LoginFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.w3._2005.atom.LoginFault
     */
    public LoginFault getFaultInfo() {
        return faultInfo;
    }

}
