
package com.googlecode.jsonwebservice.attachment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-hudson-28-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChartPort", targetNamespace = "http://jsonwebservice.googlecode.com/attachment")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChartPort {


    /**
     * 
     * @param getChartInput
     * @return
     *     returns com.googlecode.jsonwebservice.attachment.ChartOutput
     */
    @WebMethod
    @WebResult(name = "getChartOutput", partName = "getChartOutput")
    public ChartOutput getChart(
        @WebParam(name = "getChartInput", partName = "getChartInput")
        ChartInput getChartInput);

    /**
     * 
     * @param testInput
     * @return
     *     returns com.googlecode.jsonwebservice.attachment.HtmlStreamOutput
     */
    @WebMethod
    @WebResult(name = "getChartOutput", partName = "getChartOutput")
    public HtmlStreamOutput getHTMLStream(
        @WebParam(name = "testInput", partName = "testInput")
        TestInput testInput);

    /**
     * 
     * @param testInput
     * @return
     *     returns com.googlecode.jsonwebservice.attachment.XMLStreamOutput
     */
    @WebMethod
    @WebResult(name = "getChartOutput", partName = "getChartOutput")
    public XMLStreamOutput getXmlStream(
        @WebParam(name = "testInput", partName = "testInput")
        TestInput testInput);

}
